<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from /home/q/ros1/cobot_kit/scout_cobot_sim/src/scout_xarm/scout_xarm_description/scout_xarm6_sim.xacro | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="scout_cobot" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- <xacro:arg name="urdf_extras" default="empty.urdf" /> -->

    <xacro:include filename="$(find scout_xarm_description)/gazebo.gazebo"/>

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_description/scout_meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.008" />
            <geometry>
                <box size="0.925 0.38 0.21" />
            </geometry>
        </collision>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.034999999999999996" />
            <geometry>
                <box size="0.15416666666666667 0.627 0.06999999999999999" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.03" iyy="0.03" izz="0.03" ixy="0.0" ixz="0.0" iyz="0.0" />
        </inertial>
    </link>
    <!-- <joint name="chassis_link_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius - wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis_link" />
    </joint> -->
    <link name="inertial_link">
        <inertial>
            <mass value="40" />
            <!-- <mass value="50" /> -->
            <!-- <origin xyz="-0.00065 -0.085 0.062" />
            <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" /> -->
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>
    <joint name="inertial_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>
    <!-- For testing, hang the robot up in the air -->
    <!-- <link name="world" />
    <joint name="world_to_base_link=" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_description/scout_meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="0.11653" radius="0.16459" />
            </geometry>
        </collision>
    </link>
    <joint name="front_right_wheel" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin rpy="3.14 0 0" xyz="0.249 -0.29153 -0.0702" />
        <axis rpy="0 0 0" xyz="0 -1 0" />
    </joint>
    <link name="front_left_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_description/scout_meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="0.11653" radius="0.16459" />
            </geometry>
        </collision>
    </link>
    <joint name="front_left_wheel" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin rpy="0 0 0" xyz="0.249 0.29153 -0.0702" />
        <axis rpy="0 0 0" xyz="0 -1 0" />
    </joint>
    <link name="rear_left_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_description/scout_meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="0.11653" radius="0.16459" />
            </geometry>
        </collision>
    </link>
    <joint name="rear_left_wheel" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel_link" />
        <origin rpy="0 0 0" xyz="-0.249 0.29153 -0.0702" />
        <axis rpy="0 0 0" xyz="0 -1 0" />
    </joint>
    <link name="rear_right_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_description/scout_meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="0.11653" radius="0.16459" />
            </geometry>
        </collision>
    </link>
    <joint name="rear_right_wheel" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel_link" />
        <origin rpy="3.14 0 0" xyz="-0.249 -0.29153 -0.0702" />
        <axis rpy="0 0 0" xyz="0 -1 0" />
    </joint>

    <transmission name="front_right_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="front_right_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
        <joint name="front_right_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    <transmission name="front_left_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="front_left_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
        <joint name="front_left_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    <transmission name="rear_left_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="rear_left_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
        <joint name="rear_left_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    <transmission name="rear_right_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="rear_right_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
        <joint name="rear_right_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    <!-- Controller configurations -->
    <gazebo>
        <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>
    <!-- kp spring constant, kd damping constant -->
    <gazebo>
        <mu1 value="1.0" />
        <mu2 value="0.9" />
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="1 0 0" />
        <minDepth value="0.001" />
        <maxContacts value="64" />
    </gazebo>

    <link name="arm_base" />
    <joint name="world_joint" type="fixed">
        <parent link="arm_base" />
        <child link="link_base" />
        <origin rpy="0 0 -0.52" xyz="0 0 0" />
    </joint>
    <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    <material name="Red">
        <color rgba="0.8 0.0 0.0 1.0" />
    </material>
    <material name="White">
        <color rgba="1.0 1.0 1.0 1.0" />
    </material>
    <material name="Silver">
        <color rgba="0.753 0.753 0.753 1.0" />
    </material>
    <link name="link_base">
        <visual>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/base.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="White" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/base.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="0.0 0.0 0.09103" />
            <mass value="2.7" />
            <inertia ixx="0.00494875" ixy="-3.5E-06" ixz="1.25E-05" iyy="0.00494174" iyz="1.67E-06" izz="0.002219" />
        </inertial>
    </link>
    <link name="link1">
        <visual>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link1.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="White" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link1.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="-0.002 0.02692 -0.01332" />
            <mass value="2.16" />
            <inertia ixx="0.00539427" ixy="1.095E-05" ixz="1.635E-06" iyy="0.0048979" iyz="0.000793" izz="0.00311573" />
        </inertial>
    </link>
    <joint name="joint1" type="revolute">
        <parent link="link_base" />
        <child link="link1" />
        <origin rpy="0 0 0" xyz="0 0 0.267" />
        <axis xyz="0 0 1" />
        <limit effort="50.0" lower="-6.283185307179586" upper="6.283185307179586" velocity="3.14" />
        <dynamics damping="1.0" friction="1.0" />
    </joint>
    <link name="link2">
        <visual>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link2.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="White" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link2.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="0.03531 -0.21398 0.03386" />
            <mass value="1.71" />
            <inertia ixx="0.0248674" ixy="-0.00430651" ixz="-0.00067797" iyy="0.00485548" iyz="0.00457245" izz="0.02387827" />
        </inertial>
    </link>
    <joint name="joint2" type="revolute">
        <parent link="link1" />
        <child link="link2" />
        <origin rpy="-1.5708 0 0" xyz="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="50.0" lower="-2.059" upper="2.0944" velocity="3.14" />
        <dynamics damping="1.0" friction="1.0" />
    </joint>
    <link name="link3">
        <visual>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link3.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="White" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link3.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="0.06781 0.10749 0.01457" />
            <mass value="1.384" />
            <inertia ixx="0.0053694" ixy="0.0014185" ixz="-0.00092094" iyy="0.0032423" iyz="-0.00169178" izz="0.00501731" />
        </inertial>
    </link>
    <joint name="joint3" type="revolute">
        <parent link="link2" />
        <child link="link3" />
        <origin rpy="0 0 0" xyz="0.0535 -0.2845 0" />
        <axis xyz="0 0 1" />
        <limit effort="32.0" lower="-3.927" upper="0.19198" velocity="3.14" />
        <dynamics damping="1.0" friction="1.0" />
    </joint>
    <link name="link4">
        <visual>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link4.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="White" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link4.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="-0.00021 0.02578 -0.02538" />
            <mass value="1.115" />
            <inertia ixx="0.00439263" ixy="5.028E-05" ixz="1.374E-05" iyy="0.0040077" iyz="0.00045338" izz="0.00110321" />
        </inertial>
    </link>
    <joint name="joint4" type="revolute">
        <parent link="link3" />
        <child link="link4" />
        <origin rpy="-1.5708 0 0" xyz="0.0775 0.3425 0" />
        <axis xyz="0 0 1" />
        <limit effort="32.0" lower="-6.283185307179586" upper="6.283185307179586" velocity="3.14" />
        <dynamics damping="1.0" friction="1.0" />
    </joint>
    <link name="link5">
        <visual>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link5.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="White" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link5.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="0.05428 0.01781 0.00543" />
            <mass value="1.275" />
            <inertia ixx="0.001202758" ixy="0.000492428" ixz="-0.00039147" iyy="0.0022876" iyz="-1.235E-04" izz="0.0026866" />
        </inertial>
    </link>
    <joint name="joint5" type="revolute">
        <parent link="link4" />
        <child link="link5" />
        <origin rpy="1.5708 0 0 " xyz="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="32.0" lower="-1.69297" upper="3.141592653589793" velocity="3.14" />
        <dynamics damping="1.0" friction="1.0" />
    </joint>
    <link name="link6">
        <visual>
            <geometry>
                <mesh filename="package://scout_xarm_description/xarm6_meshes/visual/link6.stl" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="Silver" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://xarm_description/meshes/collision/end_tool.STL" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0.00064 -0.00952" />
            <mass value="0.1096" />
            <inertia ixx="4.5293E-05" ixy="0" ixz="0" iyy="4.8111E-05" iyz="0" izz="7.9715E-05" />
        </inertial>
    </link>
    <joint name="joint6" type="revolute">
        <parent link="link5" />
        <child link="link6" />
        <origin rpy="-1.5708 0 0" xyz="0.076 0.097 0" />
        <axis xyz="0 0 1" />
        <limit effort="20.0" lower="-6.283185307179586" upper="6.283185307179586" velocity="3.14" />
        <dynamics damping="1.0" friction="1.0" />
    </joint>
    <link name="link_eef" />
    <joint name="joint_eef" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <parent link="link6" />
        <child link="link_eef" />
    </joint>
    <transmission name="tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint1">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor1">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>100</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="tran2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint2">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor2">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>100</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="tran3">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint3">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor3">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>100</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="tran4">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint4">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor3">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>100</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="tran5">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint5">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor5">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>100</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="tran6">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint6">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor6">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>100</mechanicalReduction>
        </actuator>
    </transmission>
    <gazebo reference="link_base">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="link1">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="link2">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="link3">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="link4">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="link5">
        <selfCollide>true</selfCollide>
    </gazebo>
    <gazebo reference="link6">
        <selfCollide>true</selfCollide>
    </gazebo>
    <link name="box_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0.017247 -0.0057664 0.13638" />
            <mass value="2.1688" />
            <inertia ixx="0.019403" ixy="-1.1237E-05" ixz="-0.00039599" iyy="0.066236" iyz="5.3962E-07" izz="0.078079" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_base/meshes/base_link.STL" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.12" />
            <geometry>
                <box size="0.650 0.270 0.250" />
            </geometry>
            <!--<origin
        xyz="0.02 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh filename="package://scout_xarm_base/meshes/base_link.STL" />
      </geometry>-->
        </collision>
    </link>
    <link name="laser_Link">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.00029458 -1.102E-05 0.035775" />
            <mass value="0.58508" />
            <inertia ixx="0.00062907" ixy="-3.4247E-08" ixz="6.994E-08" iyy="0.00063026" iyz="-4.8147E-08" izz="0.00074925" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_base/meshes/laser_Link.STL" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.04" />
            <geometry>
                <cylinder length="0.09" radius="0.03" />
            </geometry>
        </collision>
    </link>
    <joint name="laser_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0.37655 2.1023E-05 0.003" />
        <parent link="box_link" />
        <child link="laser_Link" />
        <axis xyz="0 0 0" />
    </joint>
    <link name="display_Link">
        <inertial>
            <origin rpy="0 0 0" xyz="0.0013019 -6.9629E-05 0.00060167" />
            <mass value="0.58424" />
            <inertia ixx="0.0047864" ixy="1.6495E-08" ixz="1.4213E-06" iyy="0.0014088" iyz="8.2645E-08" izz="0.0034011" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_base/meshes/display_Link.STL" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_xarm_base/meshes/display_Link.STL" />
            </geometry>
        </collision>
    </link>
    <joint name="display_joint" type="fixed">
        <origin rpy="0 -0.28807 3.1416" xyz="-0.40294 -0.00097898 0.18999" />
        <parent link="box_link" />
        <child link="display_Link" />
        <axis xyz="0 0 0" />
    </joint>
    <link name="dummy_base_link" />
    <joint name="dummy_base_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
        <parent link="dummy_base_link" />
        <child link="base_link" />
    </joint>

    <transmission name="left_outer_knuckle_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_outer_knuckle_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_outer_knuckle_joint_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>
    <!-- Mimic joint plugin -->
    <gazebo>
        <plugin filename="libroboticsgroup_upatras_gazebo_mimic_joint_plugin.so" name="mimic_dh_robotics_ag95_3">
            <joint>left_outer_knuckle_joint</joint>
            <mimicJoint>right_outer_knuckle_joint</mimicJoint>
            <multiplier>1</multiplier>
            <hasPID />
        </plugin>
    </gazebo>
    <gazebo reference="ag95_base_link">
        <material>Gazebo/Grey</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="ag95_body">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="left_outer_knuckle">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="left_inner_knuckle">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="left_finger">
        <material>Gazebo/Grey</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="right_outer_knuckle">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="right_inner_knuckle">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="right_finger">
        <material>Gazebo/Grey</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="left_outer_knuckle_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="left_finger_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="left_inner_knuckle_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="left_inner_knuckle_to_finger_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="right_outer_knuckle_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="right_finger_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="right_inner_knuckle_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="right_inner_knuckle_to_finger_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <!-- base link flange -->
    <link name="ag95_base_link">
        <!-- <inertial>
        <origin xyz="7.892486664218268e-13 9.73814800116557e-05 0.0030311891257515876" rpy="0 0 0" />
        <mass value="0.18321316702693136" />
        <inertia ixx="4e-05" iyy="0.000121" izz="0.000158" ixy="0.0" iyz="0.0" ixz="-0.0" />
      </inertial> -->
        <inertial>
            <origin rpy="0 0 0" xyz="7.892486664218268e-13 9.73814800116557e-05 0.0030311891257515876" />
            <mass value="0.05335674905975589" />
            <inertia ixx="1.1649107960000001e-05" ixy="0.0" ixz="-0.0" iyy="3.5238551579e-05" iyz="0.0" izz="4.6013976442e-05" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/base_link.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/base_link.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>
    <!-- main body of gripper -->
    <link name="ag95_body">
        <!-- <inertial>
        <origin xyz="0.040363309423792425 0.014263796342398428 0.04377145101823153" rpy="0 0 0" />
        <mass value="2.681074820833332" />
        <inertia ixx="0.003857" iyy="0.004463" izz="0.001562" ixy="-3e-06" iyz="-2e-06" ixz="-9e-06" />
      </inertial> -->
        <inertial>
            <origin rpy="0 0 0" xyz="0.040363309423792425 0.014263796342398428 0.04377145101823153" />
            <mass value="0.7808032509181286" />
            <inertia ixx="0.001123265235043" ixy="-8.736830970000001e-07" ixz="-2.621049291e-06" iyy="0.001299749220637" iyz="-5.82455398e-07" izz="0.00045489766583800003" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0.0405 0.0143 -0.0147" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/gripper_body.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0405 0.0143 -0.0147" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/gripper_body.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>
    <joint name="ag95_body_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.0405 -0.0143 0.0147" />
        <parent link="ag95_base_link" />
        <child link="ag95_body" />
    </joint>
    <link name="left_outer_knuckle">
        <inertial>
            <origin rpy="0 0 0" xyz="0.027678515816713697 0.008750002359538555 -4.432690447753185e-07" />
            <mass value="0.0589066057773107" />
            <inertia ixx="1e-06" ixy="0.0" ixz="-0.0" iyy="1.7e-05" iyz="0.0" izz="1.7e-05" />
        </inertial>
        <!-- <inertial>
          <origin xyz="0.027678515816713697 0.008750002359538555 -4.432690447753185e-07" rpy="0 0 0" />
          <mass value="${0.0589066057773107*0.44684369179}" />
          <inertia ixx="${1e-06*0.44684369179}" iyy="${1.7e-05*0.44684369179}" izz="${1.7e-05*0.44684369179}" ixy="${0.0*0.44684369179}" iyz="${0.0*0.44684369179}" ixz="${-0.0*0.44684369179}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.036673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/outer_knuckle.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.036673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/outer_knuckle.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <link name="left_inner_knuckle">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.001773347637755853 0.025399999999162655 0.028950024725163018" />
            <mass value="0.07116672022913799" />
            <inertia ixx="3.7e-05" ixy="0.0" ixz="0.0" iyy="1.7e-05" iyz="-0.0" izz="2.1e-05" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.001773347637755853 0.025399999999162655 0.028950024725163018" rpy="0 0 0" />
          <mass value="${0.07116672022913799*0.44684369179}" />
          <inertia ixx="${3.7e-05*0.44684369179}" iyy="${1.7e-05*0.44684369179}" izz="${2.1e-05*0.44684369179}" ixy="${0.0*0.44684369179}" iyz="${-0.0*0.44684369179}" ixz="${0.0*0.44684369179}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.016 0.0254 -0.10586" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/inner_knuckle.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.016 0.0254 -0.10586" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/inner_knuckle.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <link name="left_finger">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.013763205176003518 0.008750002316393751 0.007315452388518454" />
            <mass value="0.035304126564626004" />
            <inertia ixx="2e-06" ixy="0.0" ixz="1e-06" iyy="4e-06" iyz="-0.0" izz="3e-06" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.013763205176003518 0.008750002316393751 0.007315452388518454" rpy="0 0 0" />
          <mass value="${0.035304126564626004*0.14953484502}" />
          <inertia ixx="${2e-06*0.14953484502}" iyy="${4e-06*0.14953484502}" izz="${3e-06*0.14953484502}" ixy="${0.0*0.14953484502}" iyz="${-0.0*0.14953484502}" ixz="${1e-06*0.14953484502}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.091673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.091673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>
    <link name="left_finger_pad">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.0022695421476374017 2.3166990085415594e-09 0.00779073905191241" />
            <mass value="0.047823655444711066" />
            <inertia ixx="5e-06" ixy="-0.0" ixz="0.0" iyy="4e-06" iyz="0.0" izz="2e-06" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.0022695421476374017 2.3166990085415594e-09 0.00779073905191241"
            rpy="0 0 0" />
          <mass value="${0.047823655444711066*0.14953484502}" />
          <inertia ixx="${5e-06*0.14953484502}" iyy="${4e-06*0.14953484502}" izz="${2e-06*0.14953484502}" ixy="${-0.0*0.14953484502}" iyz="${0.0*0.14953484502}" ixz="${0.0*0.14953484502}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.0705 -0.0 -0.12056" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/finger_pad.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.0705 -0.0 -0.12056" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/finger_pad.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <joint name="left_finger_joint" type="revolute">
        <origin rpy="0 0.7800050960087859 0" xyz="0.055 0.0 0.0" />
        <parent link="left_outer_knuckle" />
        <child link="left_finger" />
        <axis xyz="0.0 1.0 -0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <joint name="left_inner_knuckle_joint" type="revolute">
        <origin rpy="0 0.7907912307861107 0.0" xyz="0.0565 -0.0111 0.09116" />
        <parent link="ag95_body" />
        <child link="left_inner_knuckle" />
        <axis xyz="0.0 -1.0 -0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <!-- This joint closes the kinematic loop. Since loops are not allowed in URDF, but they are
      allowed in SDF, this is an SDF fragment. -->
    <gazebo>
        <joint name="left_inner_knuckle_to_finger_joint" type="revolute">
            <pose>-0.020673 0 0.007524 0 0 0</pose>
            <axis>
                <xyz>0 1 0</xyz>
                <use_parent_model_frame>false</use_parent_model_frame>
            </axis>
            <parent>left_inner_knuckle</parent>
            <child>left_finger</child>
        </joint>
    </gazebo>
    <joint name="left_inner_finger_pad_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.021173 0.00875 0.022224" />
        <parent link="left_finger" />
        <child link="left_finger_pad" />
    </joint>
    <joint name="left_outer_knuckle_joint" type="revolute">
        <origin rpy="0 -0.7800050960087859 0" xyz="0.077173 0.00555 0.083636" />
        <parent link="ag95_body" />
        <child link="left_outer_knuckle" />
        <axis xyz="-0.0 -1.0 0.0" />
        <limit effort="50.0" lower="0" upper="0.93" velocity="2.0" />
    </joint>
    <joint name="right_finger_joint" type="revolute">
        <origin rpy="0 0.7800050960087859 0" xyz="0.055 0.0 0.0" />
        <parent link="right_outer_knuckle" />
        <child link="right_finger" />
        <axis xyz="0.0 1.0 -0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <joint name="right_inner_knuckle_joint" type="revolute">
        <origin rpy="0 0.7907912307861107 -3.141592653589793" xyz="0.0245 0.0397 0.09116" />
        <parent link="ag95_body" />
        <child link="right_inner_knuckle" />
        <axis xyz="0.0 -1.0 -0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <!-- This joint closes the kinematic loop. Since loops are not allowed in URDF, but they are
      allowed in SDF, this is an SDF fragment. -->
    <gazebo>
        <joint name="right_inner_knuckle_to_finger_joint" type="revolute">
            <pose>-0.020673 0 0.007524 0 0 0</pose>
            <axis>
                <xyz>0 1 0</xyz>
                <use_parent_model_frame>false</use_parent_model_frame>
            </axis>
            <parent>right_inner_knuckle</parent>
            <child>right_finger</child>
        </joint>
    </gazebo>
    <joint name="right_inner_finger_pad_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.021173 0.00875 0.022224" />
        <parent link="right_finger" />
        <child link="right_finger_pad" />
    </joint>
    <link name="right_outer_knuckle">
        <inertial>
            <origin rpy="0 0 0" xyz="0.027678515816713697 0.008750002359538555 -4.432690447753185e-07" />
            <mass value="0.0589066057773107" />
            <inertia ixx="1e-06" ixy="0.0" ixz="-0.0" iyy="1.7e-05" iyz="0.0" izz="1.7e-05" />
        </inertial>
        <!-- <inertial>
          <origin xyz="0.027678515816713697 0.008750002359538555 -4.432690447753185e-07" rpy="0 0 0" />
          <mass value="${0.0589066057773107*0.44684369179}" />
          <inertia ixx="${1e-06*0.44684369179}" iyy="${1.7e-05*0.44684369179}" izz="${1.7e-05*0.44684369179}" ixy="${0.0*0.44684369179}" iyz="${0.0*0.44684369179}" ixz="${-0.0*0.44684369179}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.036673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/outer_knuckle.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.036673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/outer_knuckle.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <link name="right_inner_knuckle">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.001773347637755853 0.025399999999162655 0.028950024725163018" />
            <mass value="0.07116672022913799" />
            <inertia ixx="3.7e-05" ixy="0.0" ixz="0.0" iyy="1.7e-05" iyz="-0.0" izz="2.1e-05" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.001773347637755853 0.025399999999162655 0.028950024725163018" rpy="0 0 0" />
          <mass value="${0.07116672022913799*0.44684369179}" />
          <inertia ixx="${3.7e-05*0.44684369179}" iyy="${1.7e-05*0.44684369179}" izz="${2.1e-05*0.44684369179}" ixy="${0.0*0.44684369179}" iyz="${-0.0*0.44684369179}" ixz="${0.0*0.44684369179}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.016 0.0254 -0.10586" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/inner_knuckle.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.016 0.0254 -0.10586" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/inner_knuckle.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <link name="right_finger">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.013763205176003518 0.008750002316393751 0.007315452388518454" />
            <mass value="0.035304126564626004" />
            <inertia ixx="2e-06" ixy="0.0" ixz="1e-06" iyy="4e-06" iyz="-0.0" izz="3e-06" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.013763205176003518 0.008750002316393751 0.007315452388518454" rpy="0 0 0" />
          <mass value="${0.035304126564626004*0.14953484502}" />
          <inertia ixx="${2e-06*0.14953484502}" iyy="${4e-06*0.14953484502}" izz="${3e-06*0.14953484502}" ixy="${0.0*0.14953484502}" iyz="${-0.0*0.14953484502}" ixz="${1e-06*0.14953484502}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.091673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.091673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>
    <link name="right_finger_pad">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.0022695421476374017 2.3166990085415594e-09 0.00779073905191241" />
            <mass value="0.047823655444711066" />
            <inertia ixx="5e-06" ixy="-0.0" ixz="0.0" iyy="4e-06" iyz="0.0" izz="2e-06" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.0022695421476374017 2.3166990085415594e-09 0.00779073905191241"
            rpy="0 0 0" />
          <mass value="${0.047823655444711066*0.14953484502}" />
          <inertia ixx="${5e-06*0.14953484502}" iyy="${4e-06*0.14953484502}" izz="${2e-06*0.14953484502}" ixy="${-0.0*0.14953484502}" iyz="${0.0*0.14953484502}" ixz="${0.0*0.14953484502}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.0705 -0.0 -0.12056" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/finger_pad.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.0705 -0.0 -0.12056" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/finger_pad.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <joint name="right_outer_knuckle_joint" type="revolute">
        <origin rpy="0 -0.7800050960087859 3.141592653589793" xyz="0.003827000000000011 0.02305 0.083636" />
        <parent link="ag95_body" />
        <child link="right_outer_knuckle" />
        <axis xyz="-0.0 -1.0 0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <joint name="gripper_base_joint" type="fixed">
        <parent link="link6" />
        <child link="ag95_base_link" />
        <origin rpy="0.0 0.0 1.57" xyz="0.0 0.0 0.01" />
    </joint>
    <joint name="scout_with_xarm" type="fixed">
        <origin rpy="0 0 0.52" xyz="0.212 0 0.26" />
        <parent link="base_link" />
        <child link="arm_base" />
    </joint>
    <joint name="scout_with_box" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.113" />
        <parent link="base_link" />
        <child link="box_link" />
    </joint>
    <transmission name="trans_left_finger_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_finger_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_finger_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_left_inner_knuckle_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_inner_knuckle_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_inner_knuckle_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_right_finger_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_finger_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_finger_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_right_inner_knuckle_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_inner_knuckle_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_inner_knuckle_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_right_outer_knuckle_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_outer_knuckle_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_outer_knuckle_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


    <link
    name="hand_cam">
    <inertial>
      <origin
        xyz="0.0009804 0.025556 -0.036977"
        rpy="0 0 0" />
      <mass
        value="0.0067926" />
      <inertia
        ixx="3.7811E-05"
        ixy="2.2861E-18"
        ixz="2.2446E-19"
        iyy="9.4061E-05"
        iyz="6.1172E-06"
        izz="0.00012345" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
          <box size="0.02 0.05 0.02"/>
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 1.57 0" />
      <geometry>
        <box size="0.02 0.05 0.02"/>
      </geometry>
    </collision>
  </link>

  <joint
    name="hand_camera_joint"
    type="fixed">
    <origin
      xyz="0.07 0.0 0.0"
      rpy="0 -1.57 3.14" />
    <parent
      link="link6" />
    <child
      link="hand_cam" />
    <axis
      xyz="0 0 0" />
  </joint>


    <xacro:gazebo_depth_camera frame_prefix="hand_cam" ponits_frame="hand_camera_depth"/>
    <xacro:gazebo_rslidar frame_prefix="laser_Link" />


</robot>

