<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from /home/q/ros1/cobot_kit/scout_cobot_sim/src/scout_cr5/scout_cr5_description/scout_cr5_with_gripper.xacro | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="scout_cobot" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- <link name="dummy_link" /> -->
    <xacro:include filename="$(find scout_cr5_description)/gazebo.gazebo"/>

    <link name="arm_base">
        <inertial>
            <origin rpy="0 0 0" xyz="-8.0961E-06 0.0019103 0.028995" />
            <mass value="0.90882" />
            <inertia ixx="0.0014545" ixy="4.2968E-08" ixz="-1.8199E-07" iyy="0.001345" iyz="-6.243E-06" izz="0.002155" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/base_link.dae" />
            </geometry>
            <material name="">
                <color rgba="0 0 0 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/base_link.dae" />
            </geometry>
        </collision>
    </link>
    <!-- <joint name="dummy_joint" type="fixed">
    <parent link="dummy_link" />
    <child  link="arm_base" />
  </joint> -->
    <link name="Link1">
        <inertial>
            <origin rpy="0 0 0" xyz="-8.7268E-07 -0.0032576 -0.0076748" />
            <mass value="1.6123" />
            <inertia ixx="0.0029122" ixy="5.7387E-09" ixz="1.9945E-08" iyy="0.0028191" iyz="0.00044094" izz="0.0032836" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link1.dae" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link1.dae" />
            </geometry>
        </collision>
    </link>
    <joint name="joint1" type="revolute">
        <origin rpy="0 0 0" xyz="0 0 0.147" />
        <parent link="arm_base" />
        <child link="Link1" />
        <axis xyz="0 0 1" />
        <limit effort="100" lower="-3.14" upper="3.14" velocity="10" />
    </joint>
    <link name="Link2">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.21351 -1.3842E-06 0.14252" />
            <mass value="5.5186" />
            <inertia ixx="0.0085919" ixy="7.5552E-07" ixz="-7.8922E-07" iyy="0.027553" iyz="1.4629E-07" izz="0.028294" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link2.dae" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link2.dae" />
            </geometry>
        </collision>
    </link>
    <joint name="joint2" type="revolute">
        <origin rpy="1.5708 1.5708 0" xyz="0 0 0" />
        <parent link="Link1" />
        <child link="Link2" />
        <axis xyz="0 0 1" />
        <limit effort="100" lower="-3.14" upper="3.14" velocity="10" />
    </joint>
    <link name="Link3">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.15231 -1.4079E-07 0.022693" />
            <mass value="2.8536" />
            <inertia ixx="0.0032608" ixy="-3.2147E-10" ixz="0.00012363" iyy="0.0092967" iyz="2.9478E-10" izz="0.0095552" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link3.dae" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link3.dae" />
            </geometry>
        </collision>
    </link>
    <joint name="joint3" type="revolute">
        <origin rpy="0 0 0" xyz="-0.427 0 0" />
        <parent link="Link2" />
        <child link="Link3" />
        <axis xyz="0 0 1" />
        <limit effort="100" lower="-2.86" upper="2.86" velocity="10" />
    </joint>
    <link name="Link4">
        <inertial>
            <origin rpy="0 0 0" xyz="-3.2386E-07 -0.002077 -0.0015548" />
            <mass value="0.67058" />
            <inertia ixx="0.00066939" ixy="4.1975E-10" ixz="-1.0734E-08" iyy="0.00065424" iyz="0.00011081" izz="0.00065365" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link4.dae" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link4.dae" />
            </geometry>
        </collision>
    </link>
    <joint name="joint4" type="revolute">
        <origin rpy="0 0 -1.5708" xyz="-0.357 0 0.141" />
        <parent link="Link3" />
        <child link="Link4" />
        <axis xyz="0 0 1" />
        <limit effort="100" lower="-3.14" upper="3.14" velocity="10" />
    </joint>
    <link name="Link5">
        <inertial>
            <origin rpy="0 0 0" xyz="-3.7738E-07 -0.0045777 -0.0012971" />
            <mass value="0.7269" />
            <inertia ixx="0.00073069" ixy="-5.7806E-09" ixz="6.7132E-09" iyy="0.00071195" iyz="-0.00011926" izz="0.00071391" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link5.dae" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link5.dae" />
            </geometry>
        </collision>
    </link>
    <joint name="joint5" type="revolute">
        <origin rpy="1.5708 0 0" xyz="0 -0.116 0" />
        <parent link="Link4" />
        <child link="Link5" />
        <axis xyz="0 0 1" />
        <limit effort="100" lower="-3.14" upper="3.14" velocity="10" />
    </joint>
    <link name="Link6">
        <inertial>
            <origin rpy="0 0 0" xyz="5.0777E-11 9.3774E-05 -0.019285" />
            <mass value="0.15789" />
            <inertia ixx="7.8045E-05" ixy="6.1582E-15" ixz="6.2471E-14" iyy="7.9168E-05" iyz="-1.3822E-07" izz="0.00012951" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link6.dae" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dobot_description/meshes/cr5/Link6.dae" />
            </geometry>
        </collision>
    </link>
    <joint name="joint6" type="revolute">
        <origin rpy="-1.5708 0 0" xyz="0 0.105 0" />
        <parent link="Link5" />
        <child link="Link6" />
        <axis xyz="0 0 1" />
        <limit effort="100" lower="-6.28" upper="6.28" velocity="10" />
    </joint>
    <!-- <xacro:arg name="urdf_extras" default="empty.urdf" /> -->
    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_cr5_description/scout_meshes/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.008" />
            <geometry>
                <box size="0.925 0.38 0.21" />
            </geometry>
        </collision>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.034999999999999996" />
            <geometry>
                <box size="0.15416666666666667 0.627 0.06999999999999999" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.03" iyy="0.03" izz="0.03" ixy="0.0" ixz="0.0" iyz="0.0" />
        </inertial>
    </link>
    <!-- <joint name="chassis_link_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius - wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis_link" />
    </joint> -->
    <link name="inertial_link">
        <inertial>
            <mass value="40" />
            <!-- <mass value="50" /> -->
            <!-- <origin xyz="-0.00065 -0.085 0.062" />
            <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" /> -->
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
    </link>
    <joint name="inertial_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>
    <!-- For testing, hang the robot up in the air -->
    <!-- <link name="world" />
    <joint name="world_to_base_link=" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_cr5_description/scout_meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="0.11653" radius="0.16459" />
            </geometry>
        </collision>
    </link>
    <joint name="front_right_wheel" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin rpy="3.14 0 0" xyz="0.249 -0.29153 -0.0702" />
        <axis rpy="0 0 0" xyz="0 -1 0" />
    </joint>
    <link name="front_left_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_cr5_description/scout_meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="0.11653" radius="0.16459" />
            </geometry>
        </collision>
    </link>
    <joint name="front_left_wheel" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin rpy="0 0 0" xyz="0.249 0.29153 -0.0702" />
        <axis rpy="0 0 0" xyz="0 -1 0" />
    </joint>
    <link name="rear_left_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_cr5_description/scout_meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="0.11653" radius="0.16459" />
            </geometry>
        </collision>
    </link>
    <joint name="rear_left_wheel" type="continuous">
        <parent link="base_link" />
        <child link="rear_left_wheel_link" />
        <origin rpy="0 0 0" xyz="-0.249 0.29153 -0.0702" />
        <axis rpy="0 0 0" xyz="0 -1 0" />
    </joint>
    <link name="rear_right_wheel_link">
        <inertial>
            <mass value="3" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.7171" ixy="0" ixz="0" iyy="0.1361" iyz="0" izz="0.7171" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_cr5_description/scout_meshes/wheel_type1.dae" />
            </geometry>
        </visual>
        <collision>
            <origin rpy="1.570795 0 0" xyz="0 0 0" />
            <geometry>
                <cylinder length="0.11653" radius="0.16459" />
            </geometry>
        </collision>
    </link>
    <joint name="rear_right_wheel" type="continuous">
        <parent link="base_link" />
        <child link="rear_right_wheel_link" />
        <origin rpy="3.14 0 0" xyz="-0.249 -0.29153 -0.0702" />
        <axis rpy="0 0 0" xyz="0 -1 0" />
    </joint>
    <!-- Additional definitions -->
    <!-- <xacro:include filename="$(arg urdf_extras)" /> -->
    <!-- Additional definitions for simulation -->
    <!-- <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo> -->
    <transmission name="front_right_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="front_right_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
        <joint name="front_right_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    <transmission name="front_left_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="front_left_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
        <joint name="front_left_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    <transmission name="rear_left_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="rear_left_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
        <joint name="rear_left_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    <transmission name="rear_right_wheel_trans" type="SimpleTransmission">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="rear_right_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
        <joint name="rear_right_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
    </transmission>
    <!-- Controller configurations -->
    <gazebo>
        <plugin filename="libgazebo_ros_control.so" name="gazebo_ros_control">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>
    <!-- kp spring constant, kd damping constant -->
    <gazebo>
        <mu1 value="1.0" />
        <mu2 value="0.9" />
        <kp value="10000000.0" />
        <kd value="1.0" />
        <fdir1 value="1 0 0" />
        <minDepth value="0.001" />
        <maxContacts value="64" />
    </gazebo>

    <link name="box_link">
        <inertial>
            <origin rpy="0 0 0" xyz="0.017247 -0.0057664 0.13638" />
            <mass value="2.1688" />
            <inertia ixx="0.019403" ixy="-1.1237E-05" ixz="-0.00039599" iyy="0.066236" iyz="5.3962E-07" izz="0.078079" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_cr5_description/scout_meshes/box_link.STL" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.02 0 0.05" />
            <geometry>
                <!-- <mesh filename="package://scout_cr5_description/scout_meshes/box_link.STL" /> -->
                    <box size="0.650 0.270 0.250" />
            </geometry>
        </collision>
    </link>
    <link name="laser_Link">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.00029458 -1.102E-05 0.035775" />
            <mass value="0.58508" />
            <inertia ixx="0.00062907" ixy="-3.4247E-08" ixz="6.994E-08" iyy="0.00063026" iyz="-4.8147E-08" izz="0.00074925" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://scout_cr5_description/scout_meshes/laser_Link.STL" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0.04" />
            <geometry>
                <cylinder length="0.09" radius="0.05" />
            </geometry>
        </collision>
    </link>
    <joint name="laser_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.37655 2.1023E-05 0.003" />
        <parent link="box_link" />
        <child link="laser_Link" />
        <axis xyz="0 0 0" />
    </joint>
    <link name="dummy_base_link" />
    <joint name="dummy_base_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0.0 0.0 0.23" />
        <parent link="dummy_base_link" />
        <child link="base_link" />
    </joint>
    <transmission name="left_outer_knuckle_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_outer_knuckle_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_outer_knuckle_joint_motor">
            <mechanicalReduction>1</mechanicalReduction>
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </actuator>
    </transmission>
    <!-- Mimic joint plugin -->
    <gazebo>
        <plugin filename="libroboticsgroup_upatras_gazebo_mimic_joint_plugin.so" name="mimic_dh_robotics_ag95_3">
            <joint>left_outer_knuckle_joint</joint>
            <mimicJoint>right_outer_knuckle_joint</mimicJoint>
            <multiplier>1</multiplier>
            <hasPID />
        </plugin>
    </gazebo>
    <gazebo reference="ag95_base_link">
        <material>Gazebo/Grey</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="ag95_body">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="left_outer_knuckle">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="left_inner_knuckle">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="left_finger">
        <material>Gazebo/Grey</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="right_outer_knuckle">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="right_inner_knuckle">
        <material>Gazebo/Black</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="right_finger">
        <material>Gazebo/Grey</material>
        <kp>1000000.0</kp>
        <kd>1.0</kd>
        <mu1>1.16</mu1>
        <mu2>1.16</mu2>
        <maxVel>0.0</maxVel>
        <minDepth>0.003</minDepth>
    </gazebo>
    <gazebo reference="left_outer_knuckle_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="left_finger_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="left_inner_knuckle_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="left_inner_knuckle_to_finger_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="right_outer_knuckle_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="right_finger_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="right_inner_knuckle_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <gazebo reference="right_inner_knuckle_to_finger_joint">
        <implicitSpringDamper>true</implicitSpringDamper>
    </gazebo>
    <!-- base link flange -->
    <link name="ag95_base_link">
        <!-- <inertial>
        <origin xyz="7.892486664218268e-13 9.73814800116557e-05 0.0030311891257515876" rpy="0 0 0" />
        <mass value="0.18321316702693136" />
        <inertia ixx="4e-05" iyy="0.000121" izz="0.000158" ixy="0.0" iyz="0.0" ixz="-0.0" />
      </inertial> -->
        <inertial>
            <origin rpy="0 0 0" xyz="7.892486664218268e-13 9.73814800116557e-05 0.0030311891257515876" />
            <mass value="0.05335674905975589" />
            <inertia ixx="1.1649107960000001e-05" ixy="0.0" ixz="-0.0" iyy="3.5238551579e-05" iyz="0.0" izz="4.6013976442e-05" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/base_link.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/base_link.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>
    <!-- main body of gripper -->
    <link name="ag95_body">
        <!-- <inertial>
        <origin xyz="0.040363309423792425 0.014263796342398428 0.04377145101823153" rpy="0 0 0" />
        <mass value="2.681074820833332" />
        <inertia ixx="0.003857" iyy="0.004463" izz="0.001562" ixy="-3e-06" iyz="-2e-06" ixz="-9e-06" />
      </inertial> -->
        <inertial>
            <origin rpy="0 0 0" xyz="0.040363309423792425 0.014263796342398428 0.04377145101823153" />
            <mass value="0.7808032509181286" />
            <inertia ixx="0.001123265235043" ixy="-8.736830970000001e-07" ixz="-2.621049291e-06" iyy="0.001299749220637" iyz="-5.82455398e-07" izz="0.00045489766583800003" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0.0405 0.0143 -0.0147" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/gripper_body.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0.0405 0.0143 -0.0147" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/gripper_body.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>
    <joint name="ag95_body_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.0405 -0.0143 0.0147" />
        <parent link="ag95_base_link" />
        <child link="ag95_body" />
    </joint>
    <link name="left_outer_knuckle">
        <inertial>
            <origin rpy="0 0 0" xyz="0.027678515816713697 0.008750002359538555 -4.432690447753185e-07" />
            <mass value="0.0589066057773107" />
            <inertia ixx="1e-06" ixy="0.0" ixz="-0.0" iyy="1.7e-05" iyz="0.0" izz="1.7e-05" />
        </inertial>
        <!-- <inertial>
          <origin xyz="0.027678515816713697 0.008750002359538555 -4.432690447753185e-07" rpy="0 0 0" />
          <mass value="${0.0589066057773107*0.44684369179}" />
          <inertia ixx="${1e-06*0.44684369179}" iyy="${1.7e-05*0.44684369179}" izz="${1.7e-05*0.44684369179}" ixy="${0.0*0.44684369179}" iyz="${0.0*0.44684369179}" ixz="${-0.0*0.44684369179}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.036673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/outer_knuckle.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.036673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/outer_knuckle.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <link name="left_inner_knuckle">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.001773347637755853 0.025399999999162655 0.028950024725163018" />
            <mass value="0.07116672022913799" />
            <inertia ixx="3.7e-05" ixy="0.0" ixz="0.0" iyy="1.7e-05" iyz="-0.0" izz="2.1e-05" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.001773347637755853 0.025399999999162655 0.028950024725163018" rpy="0 0 0" />
          <mass value="${0.07116672022913799*0.44684369179}" />
          <inertia ixx="${3.7e-05*0.44684369179}" iyy="${1.7e-05*0.44684369179}" izz="${2.1e-05*0.44684369179}" ixy="${0.0*0.44684369179}" iyz="${-0.0*0.44684369179}" ixz="${0.0*0.44684369179}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.016 0.0254 -0.10586" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/inner_knuckle.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.016 0.0254 -0.10586" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/inner_knuckle.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <link name="left_finger">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.013763205176003518 0.008750002316393751 0.007315452388518454" />
            <mass value="0.035304126564626004" />
            <inertia ixx="2e-06" ixy="0.0" ixz="1e-06" iyy="4e-06" iyz="-0.0" izz="3e-06" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.013763205176003518 0.008750002316393751 0.007315452388518454" rpy="0 0 0" />
          <mass value="${0.035304126564626004*0.14953484502}" />
          <inertia ixx="${2e-06*0.14953484502}" iyy="${4e-06*0.14953484502}" izz="${3e-06*0.14953484502}" ixy="${0.0*0.14953484502}" iyz="${-0.0*0.14953484502}" ixz="${1e-06*0.14953484502}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.091673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.091673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>
    <link name="left_finger_pad">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.0022695421476374017 2.3166990085415594e-09 0.00779073905191241" />
            <mass value="0.047823655444711066" />
            <inertia ixx="5e-06" ixy="-0.0" ixz="0.0" iyy="4e-06" iyz="0.0" izz="2e-06" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.0022695421476374017 2.3166990085415594e-09 0.00779073905191241"
            rpy="0 0 0" />
          <mass value="${0.047823655444711066*0.14953484502}" />
          <inertia ixx="${5e-06*0.14953484502}" iyy="${4e-06*0.14953484502}" izz="${2e-06*0.14953484502}" ixy="${-0.0*0.14953484502}" iyz="${0.0*0.14953484502}" ixz="${0.0*0.14953484502}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.0705 -0.0 -0.12056" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/finger_pad.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.0705 -0.0 -0.12056" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/finger_pad.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <joint name="left_finger_joint" type="revolute">
        <origin rpy="0 0.7800050960087859 0" xyz="0.055 0.0 0.0" />
        <parent link="left_outer_knuckle" />
        <child link="left_finger" />
        <axis xyz="0.0 1.0 -0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <joint name="left_inner_knuckle_joint" type="revolute">
        <origin rpy="0 0.7907912307861107 0.0" xyz="0.0565 -0.0111 0.09116" />
        <parent link="ag95_body" />
        <child link="left_inner_knuckle" />
        <axis xyz="0.0 -1.0 -0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <!-- This joint closes the kinematic loop. Since loops are not allowed in URDF, but they are
      allowed in SDF, this is an SDF fragment. -->
    <gazebo>
        <joint name="left_inner_knuckle_to_finger_joint" type="revolute">
            <pose>-0.020673 0 0.007524 0 0 0</pose>
            <axis>
                <xyz>0 1 0</xyz>
                <use_parent_model_frame>false</use_parent_model_frame>
            </axis>
            <parent>left_inner_knuckle</parent>
            <child>left_finger</child>
        </joint>
    </gazebo>
    <joint name="left_inner_finger_pad_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.021173 0.00875 0.022224" />
        <parent link="left_finger" />
        <child link="left_finger_pad" />
    </joint>
    <joint name="left_outer_knuckle_joint" type="revolute">
        <origin rpy="0 -0.7800050960087859 0" xyz="0.077173 0.00555 0.083636" />
        <parent link="ag95_body" />
        <child link="left_outer_knuckle" />
        <axis xyz="-0.0 -1.0 0.0" />
        <limit effort="50.0" lower="0" upper="0.93" velocity="2.0" />
    </joint>
    <joint name="right_finger_joint" type="revolute">
        <origin rpy="0 0.7800050960087859 0" xyz="0.055 0.0 0.0" />
        <parent link="right_outer_knuckle" />
        <child link="right_finger" />
        <axis xyz="0.0 1.0 -0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <joint name="right_inner_knuckle_joint" type="revolute">
        <origin rpy="0 0.7907912307861107 -3.141592653589793" xyz="0.0245 0.0397 0.09116" />
        <parent link="ag95_body" />
        <child link="right_inner_knuckle" />
        <axis xyz="0.0 -1.0 -0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <!-- This joint closes the kinematic loop. Since loops are not allowed in URDF, but they are
      allowed in SDF, this is an SDF fragment. -->
    <gazebo>
        <joint name="right_inner_knuckle_to_finger_joint" type="revolute">
            <pose>-0.020673 0 0.007524 0 0 0</pose>
            <axis>
                <xyz>0 1 0</xyz>
                <use_parent_model_frame>false</use_parent_model_frame>
            </axis>
            <parent>right_inner_knuckle</parent>
            <child>right_finger</child>
        </joint>
    </gazebo>
    <joint name="right_inner_finger_pad_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.021173 0.00875 0.022224" />
        <parent link="right_finger" />
        <child link="right_finger_pad" />
    </joint>
    <link name="right_outer_knuckle">
        <inertial>
            <origin rpy="0 0 0" xyz="0.027678515816713697 0.008750002359538555 -4.432690447753185e-07" />
            <mass value="0.0589066057773107" />
            <inertia ixx="1e-06" ixy="0.0" ixz="-0.0" iyy="1.7e-05" iyz="0.0" izz="1.7e-05" />
        </inertial>
        <!-- <inertial>
          <origin xyz="0.027678515816713697 0.008750002359538555 -4.432690447753185e-07" rpy="0 0 0" />
          <mass value="${0.0589066057773107*0.44684369179}" />
          <inertia ixx="${1e-06*0.44684369179}" iyy="${1.7e-05*0.44684369179}" izz="${1.7e-05*0.44684369179}" ixy="${0.0*0.44684369179}" iyz="${0.0*0.44684369179}" ixz="${-0.0*0.44684369179}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.036673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/outer_knuckle.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.036673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/outer_knuckle.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <link name="right_inner_knuckle">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.001773347637755853 0.025399999999162655 0.028950024725163018" />
            <mass value="0.07116672022913799" />
            <inertia ixx="3.7e-05" ixy="0.0" ixz="0.0" iyy="1.7e-05" iyz="-0.0" izz="2.1e-05" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.001773347637755853 0.025399999999162655 0.028950024725163018" rpy="0 0 0" />
          <mass value="${0.07116672022913799*0.44684369179}" />
          <inertia ixx="${3.7e-05*0.44684369179}" iyy="${1.7e-05*0.44684369179}" izz="${2.1e-05*0.44684369179}" ixy="${0.0*0.44684369179}" iyz="${-0.0*0.44684369179}" ixz="${0.0*0.44684369179}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.016 0.0254 -0.10586" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/inner_knuckle.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.016 0.0254 -0.10586" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/inner_knuckle.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <link name="right_finger">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.013763205176003518 0.008750002316393751 0.007315452388518454" />
            <mass value="0.035304126564626004" />
            <inertia ixx="2e-06" ixy="0.0" ixz="1e-06" iyy="4e-06" iyz="-0.0" izz="3e-06" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.013763205176003518 0.008750002316393751 0.007315452388518454" rpy="0 0 0" />
          <mass value="${0.035304126564626004*0.14953484502}" />
          <inertia ixx="${2e-06*0.14953484502}" iyy="${4e-06*0.14953484502}" izz="${3e-06*0.14953484502}" ixy="${0.0*0.14953484502}" iyz="${-0.0*0.14953484502}" ixz="${1e-06*0.14953484502}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.091673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.091673 0.00875 -0.098336" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/finger.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>
    <link name="right_finger_pad">
        <inertial>
            <origin rpy="0 0 0" xyz="-0.0022695421476374017 2.3166990085415594e-09 0.00779073905191241" />
            <mass value="0.047823655444711066" />
            <inertia ixx="5e-06" ixy="-0.0" ixz="0.0" iyy="4e-06" iyz="0.0" izz="2e-06" />
        </inertial>
        <!-- <inertial>
          <origin xyz="-0.0022695421476374017 2.3166990085415594e-09 0.00779073905191241"
            rpy="0 0 0" />
          <mass value="${0.047823655444711066*0.14953484502}" />
          <inertia ixx="${5e-06*0.14953484502}" iyy="${4e-06*0.14953484502}" izz="${2e-06*0.14953484502}" ixy="${-0.0*0.14953484502}" iyz="${0.0*0.14953484502}" ixz="${0.0*0.14953484502}" />
        </inertial> -->
        <visual>
            <origin rpy="0 0 0" xyz="-0.0705 -0.0 -0.12056" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/visual/finger_pad.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="">
                <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="-0.0705 -0.0 -0.12056" />
            <geometry>
                <mesh filename="package://dh_ag95_description/meshes/collision/finger_pad.stl" scale="0.001 0.001 0.001" />
                <!-- <cylinder radius="0.001" length="0.001"/> -->
            </geometry>
        </collision>
    </link>
    <joint name="right_outer_knuckle_joint" type="revolute">
        <origin rpy="0 -0.7800050960087859 3.141592653589793" xyz="0.003827000000000011 0.02305 0.083636" />
        <parent link="ag95_body" />
        <child link="right_outer_knuckle" />
        <axis xyz="-0.0 -1.0 0.0" />
        <limit effort="50.0" lower="-0.01" upper="0.9400000000000001" velocity="2.0" />
        <mimic joint="left_outer_knuckle_joint" multiplier="1" offset="0" />
    </joint>
    <joint name="gripper_base_joint" type="fixed">
        <parent link="Link6" />
        <child link="ag95_base_link" />
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.01" />
    </joint>
    <joint name="scout_with_cr5" type="fixed">
        <origin rpy="0 0 1.5708" xyz="0.1 0 0.35" />
        <parent link="base_link" />
        <child link="arm_base" />
    </joint>
    <joint name="scout_with_box" type="fixed">
        <origin rpy="0 0 3.1415" xyz="0 0 0.113" />
        <parent link="base_link" />
        <child link="box_link" />
    </joint>
    <link name="hand_cam">
        <inertial>
            <origin rpy="0 0 0" xyz="0.0009804 0.025556 -0.036977" />
            <mass value="0.067926" />
            <inertia ixx="3.7811E-05" ixy="2.2861E-18" ixz="2.2446E-19" iyy="9.4061E-05" iyz="6.1172E-06" izz="0.00012345" />
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <box size="0.02 0.05 0.02" />
            </geometry>
            <material name="">
                <color rgba="1 1 1 1" />
            </material>
        </visual>
        <collision>
            <origin rpy="0 1.57 0" xyz="0 0 0" />
            <geometry>
                <box size="0.02 0.05 0.02" />
            </geometry>
        </collision>
    </link>
    <joint name="hand_camera_joint" type="fixed">
        <origin rpy="1.57 -1.57 0" xyz="0.0 -0.07 0.0" />
        <parent link="Link6" />
        <child link="hand_cam" />
        <axis xyz="0 0 0" />
    </joint>
    <transmission name="trans_joint1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint1">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint1_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_joint2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint2">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint2_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_joint3">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint3">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint3_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_joint4">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint4">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint4_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_joint5">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint5">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint5_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_joint6">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint6">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="joint6_motor">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_left_finger_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_finger_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_finger_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_left_inner_knuckle_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_inner_knuckle_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_inner_knuckle_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_right_finger_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_finger_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_finger_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_right_inner_knuckle_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_inner_knuckle_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_inner_knuckle_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="trans_right_outer_knuckle_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_outer_knuckle_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_outer_knuckle_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <xacro:gazebo_depth_camera frame_prefix="hand_cam" ponits_frame="hand_camera_depth"/>
    <xacro:gazebo_rslidar frame_prefix="laser_Link" />





</robot>

